name: benchmark_void_signals
description: Benchmark for void_signals
publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  reactivity_benchmark:
    path: ../..
  void_signals:
    path: ../../../packages/void_signals
